import json
from backend.database.models import Snapshot


def generate_continuation_prompt(snapshot: Snapshot, target_ai: str = "generic") -> str:
    data = json.loads(snapshot.structured_data)
    lines = []

    # header varies per AI
    headers = {
        "chatgpt": "# Continuing a project in ChatGPT\n\nI was working on this project and need to continue. Here's the full context:",
        "claude": "# Project Context for Claude\n\nPlease read this project context carefully before we continue working together:",
        "gemini": "# Project Continuation — Gemini\n\nHere is the structured context of a project I've been building. Continue from where we left off:",
        "generic": "# Project Context — Continue From Here\n\n> Generated by ContextBridge. You are continuing an existing project."
    }

    lines.append(headers.get(target_ai, headers["generic"]))
    lines.append("")

    if data.get("project_goal"):
        lines.append("## Project Goal")
        lines.append(data["project_goal"])
        lines.append("")

    if data.get("tech_stack"):
        lines.append("## Tech Stack")
        for item in data["tech_stack"]:
            lines.append(f"- {item}")
        lines.append("")

    if data.get("architecture_decisions"):
        lines.append("## Architecture Decisions")
        for d in data["architecture_decisions"]:
            decision = d.get("decision", "")
            reasoning = d.get("reasoning", "")
            if reasoning:
                lines.append(f"- **{decision}** — {reasoning}")
            else:
                lines.append(f"- {decision}")
        lines.append("")

    if data.get("completed_features"):
        lines.append("## Completed Features")
        for item in data["completed_features"]:
            lines.append(f"- ✓ {item}")
        lines.append("")

    if data.get("pending_tasks"):
        lines.append("## Pending Tasks")
        for item in data["pending_tasks"]:
            lines.append(f"- [ ] {item}")
        lines.append("")

    if data.get("known_issues"):
        lines.append("## Known Issues")
        for item in data["known_issues"]:
            lines.append(f"- ⚠ {item}")
        lines.append("")

    if data.get("constraints"):
        lines.append("## Constraints")
        for item in data["constraints"]:
            lines.append(f"- {item}")
        lines.append("")

    if data.get("key_code_references"):
        lines.append("## Key Files")
        for ref in data["key_code_references"]:
            lines.append(f"- `{ref.get('file', '')}` — {ref.get('purpose', '')}")
        lines.append("")

    # closing instruction varies per AI
    closings = {
        "chatgpt": "Please acknowledge you understand this context and ask me what to work on next.",
        "claude": "Please confirm you have understood the project context. Then ask me what I'd like to tackle from the pending tasks.",
        "gemini": "Acknowledge this context and suggest the best next step based on the pending tasks.",
        "generic": "Continue the project from the pending tasks above."
    }

    lines.append("---")
    lines.append(closings.get(target_ai, closings["generic"]))

    return "\n".join(lines)